import Head from "next/head";
import { useContext, useState } from "react";
import AddPhoto from "../components/AddPhoto";
import uiContext from "../store/ui-context";

export default function Home() {
  const [showAddPhoto, setShowAddPhoto] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/devchallenges.png" />
      </Head>

      <div className="container">
        <nav>
          <img src="/my_unsplash_logo.svg" alt="logo"></img>
          <div className="nav__navbar">
            <div className="nav__search">
              <input placeholder="Search by name"></input>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                height="48"
                width="48"
                viewBox="0 0 48 48"
              >
                <path d="M39.8 41.95 26.65 28.8q-1.5 1.3-3.5 2.025-2 .725-4.25.725-5.4 0-9.15-3.75T6 18.75q0-5.3 3.75-9.05 3.75-3.75 9.1-3.75 5.3 0 9.025 3.75 3.725 3.75 3.725 9.05 0 2.15-.7 4.15-.7 2-2.1 3.75L42 39.75Zm-20.95-13.4q4.05 0 6.9-2.875Q28.6 22.8 28.6 18.75t-2.85-6.925Q22.9 8.95 18.85 8.95q-4.1 0-6.975 2.875T9 18.75q0 4.05 2.875 6.925t6.975 2.875Z" />
              </svg>
            </div>

            <button onClick={() => setShowAddPhoto(true)}>Add a photo</button>
          </div>
        </nav>

        <div className="footer__owner">
          created by <a href="https://github.com/bashidagha">bashidagha</a> -
          devChallenges.io
        </div>
      </div>

      {showAddPhoto && <AddPhoto setShowAddPhoto={setShowAddPhoto}/>}
    </>
  );
}
