import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import AddPhoto from "../components/AddPhoto";
import Masonry, { ResponsiveMasonry } from "react-responsive-masonry";
import { onValue, ref, set } from "firebase/database";
import { database } from "../helper/DatabaseHelper";

function Home({ images }) {
  const [showAddPhoto, setShowAddPhoto] = useState(false);

  // const [images, setImages] = useState(null);

  // useEffect(() => {
  //   const starCountRef = ref(database, "/images");
  //   onValue(starCountRef, (snapshot) => {
  //     const data = snapshot.val();
  //     // console.log(data)
  //     setImages(data);
  //   });
  // }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/devchallenges.png" />
      </Head>

      <div className="container">
        <nav>
          <img src="/my_unsplash_logo.svg" alt="logo"></img>
          <div className="nav__navbar">
            <div className="nav__search">
              <input placeholder="Search by name"></input>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                height="48"
                width="48"
                viewBox="0 0 48 48"
              >
                <path d="M39.8 41.95 26.65 28.8q-1.5 1.3-3.5 2.025-2 .725-4.25.725-5.4 0-9.15-3.75T6 18.75q0-5.3 3.75-9.05 3.75-3.75 9.1-3.75 5.3 0 9.025 3.75 3.725 3.75 3.725 9.05 0 2.15-.7 4.15-.7 2-2.1 3.75L42 39.75Zm-20.95-13.4q4.05 0 6.9-2.875Q28.6 22.8 28.6 18.75t-2.85-6.925Q22.9 8.95 18.85 8.95q-4.1 0-6.975 2.875T9 18.75q0 4.05 2.875 6.925t6.975 2.875Z" />
              </svg>
            </div>

            <button className="mybtn" onClick={() => setShowAddPhoto(true)}>
              Add a photo
            </button>
          </div>
        </nav>

        <ResponsiveMasonry
          columnsCountBreakPoints={{ 350: 1, 450: 2, 800: 3, 1200: 4, 1400: 5 }}
          className="gallery"
        >
          <Masonry columnsCount={4} gutter="10px">
            {images &&
              images.map((image, i) => (
                <img key={i} src={image.url} alt={image.label} />
              ))}
          </Masonry>
        </ResponsiveMasonry>

        <div className="footer__owner">
          created by <a href="https://github.com/bashidagha">bashidagha</a> -
          devChallenges.io
        </div>
      </div>

      {showAddPhoto && <AddPhoto setShowAddPhoto={setShowAddPhoto} />}
    </>
  );
}

// This gets called on every request
export async function getServerSideProps(context) {
  // Fetch data from external API
  let images = [];

  const starCountRef = await ref(database, "/images");
  await onValue(starCountRef, (snapshot) => {
    images.push(snapshot.val());
    console.log(images);
  });

  // Pass data to the page via props
  return { props: { images } };
}

export default Home;
